# Yemen Market Integration Project Configuration

# Data settings
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  interim_path: "data/interim"  # Added for intermediate processing steps
  primary_geojson: "unified_data.geojson"
  cache_dir: ".cache"
  max_chunk_size: 10000  # For chunked processing
  backup_dir: "data/backups"  # Added for automatic backups
  
# Analysis settings
analysis:
  # Cointegration test settings
  cointegration:
    max_lags: 4
    alpha: 0.05
    trend: "c"
    method: "engle-granger"  # Default method
  
  # Threshold settings
  threshold:
    trim: 0.15
    n_grid: 300
    max_lags: 4
    alpha: 0.05
    n_bootstrap: 1000
    # M-TAR parameters
    mtar_default_threshold: 0.0
    mtar_test: true
    mtar_asymmetry_alpha: 0.05
  
  # Threshold VECM settings
  threshold_vecm:
    alpha: 0.05
    trim: 0.15
    n_grid: 300
    k_ar_diff: 2
    bootstrap_reps: 1000
    deterministic: "ci"  # Added for deterministic term specification
  
  # Spatial settings
  spatial:
    knn: 5
    conflict_weight: 0.5
    conflict_adjusted: true
    crs: 32638  # UTM Zone 38N for Yemen
    distance_threshold: 50000  # Meters
    accessibility_max_distance: 50000  # Meters
  
  # Diagnostics settings
  diagnostics:
    alpha: 0.05
    lags: 12
    bootstrap_reps: 1000
    tests: ["adf", "kpss", "pp"]  # Available stationarity tests
    
  # Structural break settings
  structural_break:
    bai_perron_max_breaks: 3
    bai_perron_min_size: 10 
    zivot_andrews_trim: 0.15
    test_both_series: true
    
  # Simulation settings for policy interventions
  simulation:
    # Exchange rate unification settings
    exchange_rate_default: "official"  # Default target rate (options: 'official', 'market', 'north', 'south', or numerical value)
    usd_cross_conversion: true  # Use USD as intermediary for conversion
    
    # Connectivity improvement settings
    conflict_reduction_default: 0.5  # Default conflict reduction factor (0-1)
    regime_boundary_penalty: 1.5  # Penalty for cross-regime connections
    
    # Sensitivity analysis settings 
    sensitivity_conflict_levels: [0.1, 0.25, 0.5, 0.75, 0.9]  # Default parameter values for sensitivity testing
    sensitivity_metrics: ["price_convergence", "integration_index", "asymmetry"]  # Default metrics to monitor
    high_sensitivity_threshold: 0.5  # CV threshold for high sensitivity classification
    
    # Robustness testing
    robustness_structural_break_test: true  # Test for structural breaks during robustness analysis
    robustness_residual_diagnostics: true   # Compare residual diagnostics during robustness analysis

  # Data cleaning settings (added section)
  data_cleaning:
    numeric_strategy: "median"
    categorical_strategy: "mode"
    date_strategy: "nearest"
    outlier_detection_method: "iqr"
    outlier_threshold: 1.5
    downcast: true
    category_min_size: 50

# Commodities of interest (in order of priority)
commodities:
  - "beans (kidney red)"
  - "beans (white)"
  - "eggs"
  - "flour"
  - "rice"
  - "sugar"
  - "wheat"

# Regional groupings
regions:
  north:
    - "amanat alasimah"
    - "sanaa"
    - "ibb"
    - "taiz"
  south:
    - "abyan"
    - "aden"
    - "lahj"
    - "shabwah"

# Visualization settings
visualization:
  color_palette: "viridis"
  figure_dpi: 300
  default_fig_width: 12
  default_fig_height: 8
  interactive_width: 800
  interactive_height: 600
  
  # Map colors
  north_color: "#1f77b4"
  south_color: "#ff7f0e"
  conflict_color: "#d62728"
  
  # Plot directories
  save_dir: "results/plots"
  formats: ["png", "pdf"]
  
  # Date formatting
  date_format: "%Y-%m"
  date_interval: "month"
  
  # Added settings for plot styles
  font_family: "sans-serif"
  title_fontsize: 14
  label_fontsize: 12
  tick_fontsize: 10
  linewidth: 1.5
  grid: true
  
  # Simulation visualization settings
  simulation_plot_dir: "results/plots/simulations"
  sensitivity_heatmap: true
  regime_comparison_palette: "Set2"
  asymmetry_plot_colors: ["#2ca02c", "#d62728"]

# Performance settings
performance:
  use_parallel: true
  n_workers: 4  # Default, will use (cpu_count - 1) if not specified
  memory_limit: "4GB"
  use_numba: true
  use_cache: true
  cache_expiration: 86400  # Cache expiration in seconds (24 hours)
  
# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/yemen_analysis.log"
  error_file: "logs/errors.log"  # Added for separate error logging
  rotation: "daily"
  backup_count: 30
  add_timestamp_to_files: true
  capture_warnings: true
  console: true  # Whether to log to console

# API settings (added section for future integration)
api:
  base_url: "https://example.com/api"
  timeout: 30
  retries: 3
  backoff_factor: 2.0